env:
  - GO111MODULE=on
  - CGO_ENABLED=0
  - DOCKER_ORG=reg.theeuwes.me
  - PROJECT_NAME=listmonk-hff
  - TAG=5.0.4

before:
  hooks:
    - make build-frontend

builds:
  - binary: listmonk
    main: ./cmd
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w -X "main.buildString={{ .Tag }} ({{ .ShortCommit }} {{ .Date }}, {{ .Os }}/{{ .Arch }})" -X "main.versionString={{ .Tag }}"

    hooks:
      # stuff executables with static assets.
      post: make pack-bin BIN={{ .Path }}

archives:
  - format: tar.gz
    files:
      - README.md
      - LICENSE

dockers:
  - use: buildx
    goos: linux
    goarch: amd64
    ids:
      - listmonk
    image_templates:
      - "{{ .Env.DOCKER_ORG }}/{{ .Env.PROJECT_NAME }}:{{ .Env.TAG }}"
    build_flag_templates:
      - --platform=linux/amd64
      - --label=org.opencontainers.image.title={{ .Env.PROJECT_NAME }}
      - --label=org.opencontainers.image.description={{ .Env.PROJECT_NAME }}
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=AGPL-3.0
    dockerfile: Dockerfile
    extra_files:
      - config.toml.sample
      - docker-entrypoint.sh

docker_manifests:
  - name_template: "{{ .Env.DOCKER_ORG }}/{{ .Env.PROJECT_NAME }}:{{ .Env.TAG}}"
    image_templates:
      - "{{ .Env.DOCKER_ORG }}/{{ .Env.PROJECT_NAME }}:{{ .Env.TAG }}"
  - name_template: "{{ .Env.DOCKER_ORG }}/{{ .Env.PROJECT_NAME }}:{{ .Env.TAG }}"
    image_templates:
      - "{{ .Env.DOCKER_ORG }}/{{ .Env.PROJECT_NAME }}:{{ .Env.TAG }}"
